spring:
  sql:
    init:
      mode: never

logging:
  level:
    root: WARN
    com.huawei.devbridge.relaycontroller: WARN
    com.huawei.devbridge.relaycontroller.RelayControllerApplication: INFO
    com.huawei.devbridge.relaycontroller.application.service: INFO
    com.huawei.devbridge.relaycontroller.common.exception: WARN
