server:
  port: 8080

spring:
  application:
    name: relay-controller
  main:
    banner-mode: off
    log-startup-info: false
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/relay_controller?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      client-type: jedis
      host: localhost
      port: 6379
      database: 0
      timeout: 3000ms

springdoc:
  swagger-ui:
    url: /openapi.yaml

mybatis-plus:
  type-aliases-package: com.huawei.devbridge.relaycontroller.infrastructure.persistence.entity
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: WARN
    com.baomidou.mybatisplus.core.toolkit.Sequence: OFF
    com.huawei.devbridge.relaycontroller.RelayControllerApplication: INFO

relay:
  domain: relayprovider.xxx.com
  default-expiration-seconds: 259200
  jwt:
    issuer: devbridge
    key-id: "1"
    private-key:
    public-keys: {}
    ott:
      ttl-seconds: 1800
      consumed-ttl-seconds: 300
    rt:
      ttl-seconds: 86400
