server:
  port: ${SERVER_PORT:8443}
  ssl:
    enabled: true
    bundle: mtls
    client-auth: need

spring:
  ssl:
    bundle:
      jks:
        mtls:
          keystore:
            location: base64:${SERVER_SSL_KEY_STORE_BASE64}
            password: ${ENC(${SERVER_SSL_KEY_STORE_PASSWORD})}
            type: PKCS12
          truststore:
            location: base64:${SERVER_SSL_TRUST_STORE_BASE64}
            password: ${ENC(${SERVER_SSL_TRUST_STORE_PASSWORD})}
            type: PKCS12
